### ISSUE TITLE
too strict?

### ISSUE THREAD

**Issue by jrochkind** [pulibrary/lcsort#1]
I'm finding this code is refusing certain LC call numbers as invalid, that I'm pretty sure are valid. 

I think one class where it does this is where the initial class number has a decimal part. LC call numbers usually start like "TL 780".  But sometimes the number has a decimal, like "TL 780.5".  If I understand it right. This second example, where the number has a ".5" on the end, is rejected by this normalizer. 

I'm still trying to wrap my head around exactly what is and isn't valid, and what the numbers mean as far as sort order.  And I'm still evaluating different code to begin with for LC sort normalization, including this one -- I might port something ndushay has from Java instead, not sure. 

But if I decide this one is my best bet, are you interested in pull requests to make it stop rejecting things that are or should be valid, to make it a bit more flexible? 

There are some other things in this gem that work a bit differently then I'd like -- I don't see the `:wellform` option as being useful. If `:wellform => true` were just the only way it worked, you could still get the behavior you want with simply `Lcsort.normalize(call_str) || call_str.upcase`.  If what you want is an upcased version of call number for calls that can't be normalized, you can do that yourself, it doesn't need to be baked into Lcsort.normalize, which can just return nil. Unless I'm missing something?

**Comment by jpstroop** [comment]
(I don't want to speak for @tampakis, but he's offline for a few days and I don't want to see this thread drop).

> I think one class where it does this is where the initial class number has a decimal part. LC call numbers usually start like "TL 780". But sometimes the number has a decimal, like "TL 780.5". If I understand it right. This second example, where the number has a ".5" on the end, is rejected by this normalizer.

If it does, that's almost certainly a bug, see, for example [1143279](http://catalog.princeton.edu/cgi-bin/Pwebrecon.cgi?BBID=1143279), which has:

``` xml
<datafield ind1="0" ind2="0" tag="852">
  <subfield code="b">st</subfield>
  <subfield code="t">1</subfield>
  <subfield code="h">TL781.5.S3</subfield>
  <subfield code="i">B54 1996</subfield>
</datafield>
```

That aside, this started as a failrly quick port of the Python version of [library-callnumber-lc](https://github.com/libraryhackers/library-callnumber-lc), but like probably everyone else out there, we have to account for extra local wierdness as well.

Taking a step back, I think it would be great if a general purpose gem/API could be built out with expected behaviors for that rare library that only has LC numbers and follows all of the rules, but implemented with some mechanism for further refining those behaviors (or even fully re-implementing the gem's API) to manage the inevitable aforementioned local weirdness. You two should probably talk about that pattern would look like, but yeah, we're open to collaborating.

**Comment by jpstroop** [comment]
Tangentially, years ago I worked with [python-stdnum](https://github.com/arthurdejong/python-stdnum), (need to validate a Slovenian VAT number, or the 2013 extention of Irish Personal Public Service Numbers anyone?), and the stardard API for a given number scheme was:

```
#validate() 
#compact()
#format()
```

Where `compact` usually returns the sortable version, if I recall. I've never run across a similar library for Ruby, but if there is one, that might be a good place to look for an already-defined interface.

**Comment by tampakis** [comment]
I'd be happy to work more on this and take pull requests. I took a quick look at the examples both of you mentioned and I got the following results back:

```
Lcsort.normalize('TL 780.5') => "TL 078050"
Lcsort.normalize('TL781.5.S3 B54 1996') => "TL 078150S300B540 000 1996" 
```

I think this is expected behavior.
If anything gets rejected the current behavior is to return the value upcased and with punctuation stripped on both ends. The `:wellform` option was put in when I wanted to get no result back because I used to index the normalized value with Traject and that seemed like it would be useful at the time.

**Comment by jrochkind** [comment]
Yeah, this stuff gets complicated fast, because lc call numbers are not very well specified in the wild.  I think creating a 'general purpose' solution is hard, because everyone has different things they care or don't care to account for, depending on their use and their local data. 

I'll probably end up writing my own solution, one way or another, too. Everything I'm finding doesn't quite do what I need for one reason or another. Things I'm looking at:
- this repo right here :)
- BillDueber's lc call number _parsing_ library, at https://github.com/billdueber/lc_callnumber .  Parsing into constituent parts is a neccesary part of creating a normalized sort key one way or another, whether you do it with a regex or an actual parser (see next), and whether you do it as a separate step or not.  I'm worried that Bill's code will be to slow for my use, since it uses a parslet parser and does a number of things i don't need. 
- ndushay's code in Java at https://github.com/sul-dlss/solrmarc-sw/blob/master/core/src/org/solrmarc/tools/CallNumUtils.java .   ndushay's code doesn't just use a regex, but uses a combination of iterative/procedural approaches. It's kind of complicated. But handles a lot of cases. And of course is in Java, when I want ruby.  The tests for that code are also helpful in understanding what it does, https://github.com/sul-dlss/solrmarc-sw/blob/master/core/test/src/org/solrmarc/tools/CallNumberUnitTests.java

I really want to do it as a regex, but this regex is rejecting things I want it to accept that Bill's parser also accepts and parses correctly. Getting to the bottom of it is hugely confusing.  I'll keep comparing everything and plowing through it, and comparing how different code handles different call numbers. 

---

As an aside, :wellform, which is really a separate issue: I still suggest you don't need a wellform option built in, if you stick with returning nil for ill-formed, you can still get the same behavior yourself:

```
  x = Lcsort.normalize(ill_formed, :wellform => true)
  # This will do the exact same thing, with no need for a wellform option feature:
  x = Lcsort.normalize(ill_formed) || ill_formed.upcase
```

**Comment by jrochkind** [comment]
PS: Your right, you can handle "decimal" class numbers sometimes, clearly. I haven't quite figured out why you are rejecting things I think you should be accepting, including some call numbers taken directly from the LC online catalog. Which I didn't make a note of the exact call numbers, I'm afraid. Needs more investigation. A lot. sigh.

**Comment by jpstroop** [comment]
:wink:

**Comment by jrochkind** [comment]
And yet another regex example, in Perl, to look at.

https://metacpan.org/pod/Library::CallNumber::LC

Bill Dueber says that's an evolution of the last best regex based approach he worked on.

**Comment by jrochkind** [comment]
Although that one maybe looks a lot like yours, ha.

**Comment by jrochkind** [comment]
Here are a few call numbers that aren't parseable with this library, that I believe are legal LC call numbers. In general, I think most of these can be parsed by Bill Dueber's lc_callnumber parsing library. 

```
QA76.5915 .D68 2011
DT546.175.N63 2011
HD30.213 .T87 2011
```

I think maybe only two numbers after the decimal point in the class number are allowed?  QA 76.5915 => bad, but QA 76.59 would be okay. But I don't think there is in fact a two-number restriction in lc call numbers like this. 

Here's an example straight from LC's own catalog, LCCN 2010028310 , catalog.loc.gov doesn't have persistent URL's so I can't give you a link, but just enter that number at catalog.loc.gov. 

Call number directly in the record for that LCCN is: QA76.884 .L36 2011

That is not parseable by this library. 

If it is just an issue of number of digits past the decimal in the class number -- fixing it would also require making more space in the generated sort key, which would make sort keys incompatible with previous sort keys.

**Comment by tampakis** [comment]
Yes you are right @jrochkind, thanks for finding this! Just as you said, this parser assumes that a decimal is no more than 2 digits long, which doesn't seem to actually be an LC requirement. Do you think it's reasonable to change it to allow up to 4 digits for the decimal?

**Comment by jrochkind** [comment]
At least 4 definitely seem to be required, I don't know if more than 4 is possible, we might have to ask a cataloger. Or wait and see if I notice any in my data. But 4, yep, sounds right. 

It does require making more space in the sort key, so it's a backwards incompat change -- sortkeys generated after the change may not be compatible (sort correctly when intermixed with) sortkeys from before the change.  So i wonder if we shouldn't make even more space than 4, just in case to avoid having to do it again.  Stanford's code allows 6 after the decimal place (and four before), maybe do that to be safe?

I think I'm going to submit a PR to fix the indentation in the source, it's all over the place now making it hard to read. 

I also _really_ want to get rid of the wellform option and make it behave as if wellform true all the time. It makes the code a lot more complicated with all those nested ifs, and I really think it's not required.

**Comment by tampakis** [comment]
I agree about the wellform option. I was just looking at it and it is pretty messy without any real benefit. I'll remove it.

I'm ok with 6 digits as well. Although it's easy to change that value within the parser, it's not necessarily so easy to change all the generated sort keys, so it's probably a good idea to be sure we won't need any more digits later.

**Comment by jrochkind** [comment]
Cool. 

If there ARE more digits than 6 (saying 6 is set as the width in the sort key), I think I'd rather it truncate to 6 and return a sortkey anyway, instead of refusing.  The effect of that will be that extra digits will be ignored for sorting, ".1234564444" will sort equivalently to ".1234560000" or ".123456".  Which is what I'd want, rather than giving up on it entirely. 

But if that's not universally desired, it might require an option (horrors, options make things more complciated), and I'm not sure I have any such data with more than 6 anyway (or if anyone does!), so probably better to just rest on this until someone actually notices a need! 

Do you have any idea what the :bottomout option actually does?  I'm trying to figure out what it's for, as well as what the extra logic that uses it by default when there's "extra" actually does.  But  I can go back to the python/perl and see if there are any docs, or just keep experimenting with it and looking at the code.

**Comment by tampakis** [comment]
I like the idea of truncating just in case something actually has more than 6 digits so at least you get a sorted value back.

The :bottomout option allows for range queries. For example, let's say a user wants to retrieve all records that have `A 545 .B2` as the root. This can be done by getting the regular normalized and 'bottomout' versions:

```
# with six digits for decimal
Lcsort.normalize('A 545 .B2')  => "A  0545000000B200" 
Lcsort.normalize('A 545 .B2', :bottomout => true) => "A  0545000000B299~999~999"
```

These values constitute the beginning and end of the normalized range that would match the given root. Then the user can retrieve all normalized call numbers within this range. We don't use this feature, but I kept it in when I was porting the code from python.

**Comment by jrochkind** [comment]
Ah, so the 'bottomout' version is actually the UPPER end of the range desired, not the lower?  I wonder where calling that 'bottomout' comes from.
