### ISSUE TITLE
intent of "remove non alphanumeric leading and trailing"

### ISSUE THREAD

**Issue by jrochkind** [pulibrary/lcsort#6]
Hi, can we talk about commit eb0dcb90c , "remove non alphanumeric leading and trailing", which does a:

```
 .gsub(/^[^A-Z0-9]*|[^A-Z0-9]*$/, '')
```

What's the intent of this, what sort of input did you have that required it? 

Thinking about the fact that this also removes all non-ascii --- non-ascii isn't neccesarily going to work right with this script anyway, but simply stripping it isn't neccesarily the right solution. 

I'm not sure this line is a problem... but I'm getting nervous about not being sure what is or is not a problem, as I get deeper into this,and see how easy it is to mess up weird cases. 

Looking at your three tested examples:
- `.A20`  => To me, this reads like a typo, it's a cutter without a class number. But after your 'correction', it will be parsed as if it were class number `A 20`. I think it's unlikely to be so though, I've never seen a leading period like this used intentionally. I think `.A20` is more likely to be a cutter missing it's actual class numbers, which should be thrown out as invalid rather than read as "A 20". 
- `B31.4 1992.`  =>  Stripping the trailing period is unneccesary -- the existing logic without the stripping will still recognize this as a valid call number, and in fact will still do exactly the same thing with it, as the existing logic strips non-alphanumeric from the 'extra' portion. 
-    'Microfilm.'  => invalid anyway, it's not Lcsort's responsibility to do anything particularly useful with things that simply aren't lc call numbers. 

So I'm inclined to suggest reversing that gsub. What do you think?

**Comment by jrochkind** [comment]
PS:  While I don't generally do "test-driven development", this kind of confusing code is one place where I find writing a failing test first handy.  Writing a failing test first in this case would have shown that `B31.4 1992.` is treated exactly the same before and after eb0dcb9 .

**Comment by tampakis** [comment]
I had added that commit because there were call numbers with leading and trailing periods that were throwing off the sorting. I think most of them were not valid LC though. I'll take a look and will let you know if there is a good case for keeping this in. Otherwise I'm fine with including the gsub in as part of `x = Lcsort.normalize(callno) || callno.upcase.gsub(/^[^A-Z0-9]*|[^A-Z0-9]*$/, '')`

**Comment by jrochkind** [comment]
Cool. Yep, you could always just normalize it yourself first too:

```
  = Lcsort.normalize( callno.upcase.gsub(/^[^A-Z0-9]*|[^A-Z0-9]*$/, ''))
```

Would do exaclty what's there now, but with you having to be explicit about, and choosing to, do it instead of Lcsort doing it for you. 

I think actual call number data and practices vary enough that most people are going to have to do SOME pre-normalization on the way in, unique to their circumstances. For instance I'm going to have to remove some local prefixes from mine first, before sending to Lcsort.normalize. Trying to put too much in a shared lcsort gem will just make it less general purpose.

**Comment by jpstroop** [comment]
Perhaps normalize could take a block, i.e.,

``` ruby
normalize(call_no) do |cn|
  # my special stuff, filters, whatever here
end
```

?

**Comment by jrochkind** [comment]
Honestly, I don't think it's necessary and would try to keep it simple.   I don't see a huge advantage to that over the API client developer just writing:

```
normalize(do_my_special_stuff call_no)
```

With their own do_my_speical_tuff method, if they want to do their own normalization and filters first.  It's not really any less readable or less convenient, and avoids feature bloat in Lcsort. Just write ruby.

**Comment by jpstroop** [comment]
Sure, that's fine. Just an idea (and I always feel cool when I get to implement something that takes a block :wink:).
