### ISSUE TITLE
not sure how to handle this local variation, letters following cutter

### ISSUE THREAD

**Issue by jrochkind** [pulibrary/lcsort#7]
In my catalog, sometimes letter suffixes have been added to cutters. 

Say, `BA 101.1 A123a`

Note the `a` on the end. It doesn't have to be a, and sometimes is more than one letter. 

This definitely isn't standard LC call numbering, it's a variation. Local catalogers aren't sure how common this practice might be. The Stanford call number parsing code doesn't handle it, I don't think. Bill Dueber's parsing code doesn't parse it 'correctly', although it doesn't reject it. 

I need to handle it somehow. It doesn't matter too much to me if the letters are treated correctly for sorting, or just ignored as if they weren't there. But currently, the letters cause the call number not to match the initial regex and be rejected entirely. 

I'm not really sure what to do.  Modifying Lcsort to handle this local variation doesn't feel good; but neither does forking Lcsort to my own custom version. I can't figure out any good way to make Lcsort locally customizable -- there'd have to be an option for changing the regex AND an option for supplying custom logic for turning the cutter into a sortkey. It could be done, but would be a lot of work and make the code a lot more complicated. It would be a lot easier to simply make Lcsort handle my local variation out of the box, but yeah, it feels not great.  But I'm leaning to that just because it would make things easier for me at least, and I don't think would cause any problems for anyone else. 

Any thoughts or advice?

**Comment by jrochkind** [comment]
Added wrinkle that might justify adding cutter-letter-suffix recognition to the main Lcsort:

NLM call numbers look a _lot_ like LC call numbers, but differ in some ways. One way they appear to differ is that cutters sometimes have letter suffixes (for serials only, I think). 

http://www.nlm.nih.gov/tsd/cataloging/trainingcourses/classification/mod9_050.html

Adding recognition of letter suffixes in cutters is necessary for parsing NLM call numbers (I'm not sure if it's sufficient as well as necessary, but I think it might be). 

Man, call numbers are a mess. 

I'm inclined to submit a PR where letter suffixes on cutters are recognized -- I don't care too much if they wind up sorting 'correctly', or the letter suffixes are just ignored. "Correctly" means A123a sorts after A123 but before A1231 or A124.  "Ignore" would mean sort A123a just like A123, it's not determined which comes first, the suffix just gets stripped. Either is fine with me.

**Comment by jrochkind** [comment]
Bah, nevermind, NLM diverges in several other ways too.

**Comment by tampakis** [comment]
I think suffixes like the one in the example you mentioned are fairly common practice. We have them also, but usually they are part of the "extra" portion so they don't interpreted as another cutter. I think in this case a suffix that appears as part of a cutter should be put into the extra.

**Comment by jrochkind** [comment]
Thansk for the feedback!

It's not as easy as "putting it in the extra", for my use case.  "The extra" is at the end of the entire call number, but in my case at least, these extra letters can be internal. 

```
QA 101.1 A101zz  B202
```

Note the `zz` is the kind of suffix I'm talking about. 

I'll probably submit a PR for it anyway though, see what we think. I may give up and _ignore_ those suffixes -- it's really tricky to actually have them sort 'correctly', I've been trying, at some point I'll give up and decide it's good enough if `QA 101.1 A101zz B202` just sorts exactly the same as `QA 101.1 A101 B202` -- right now, it doesn't parse at all.

**Comment by tampakis** [comment]
Actually I think it is as easy as "putting in the extra." The hard part I believe is being able to capture the suffixes (which it sounds like you need to do either way). However, if you can do that, moving it to the end of the extra (or maybe the beginning of the extra?) would give you the desired result.

```
$ cn1 = Lcsort.normalize("QA 101.1 A101 B202") => "QA 0101100000A101B202" 
$ cn2 = Lcsort.normalize("QA 101.1 A101 B205") => "QA 0101100000A101B205"
```

Imagine a function that gives you the captured suffix and the call number with such suffix removed:

```
$ suffix, cn_stripped = capture_suffix("QA 101.1 A101zz B202")
$ cn3 = Lcsort.normalize(cn_stripped) + suffix => "QA 0101100000A101B202zz" 
$ [cn1, cn2, cn3].sort => [cn1, cn3, cn2]
```

**Comment by jrochkind** [comment]
Hm, I think that woudln't actually sort correctly. Here's a proper sort order:
- QA 101.1 A101
- QA 101.1 A101a
- QA 101.1 A101b
- QA 101.1 A101 B101

I don't think your approach would result in that sort order?  Although frankly at this point I'd be happy to simply strip/ignore the suffix, and treat `QA 101.1 A101a` as sorting identically to `QA 101.1 A101`, as opposed to not parsing. Which would be fairly easy to implement as built-in to lcsort. 

REALLY I'm considering just ignoring it entirely at this point and letting those call numbers simply be rejected, oh well. There are so many idiosyncratic call numbers we have falling through the cracks anyway, I think maybe that's just how it's gonna be.

**Comment by jrochkind** [comment]
Still not quite sure what to do with all this -- I'm considering whether we want to turn the code into actual object-oriented class, so you'd do something like this:

   normalizer = LCSort.new
   normalizer.normalize(call_number)

That would make it easier to provide configuration options to parse in different ways. Maybe:

```
normalizer.allow_letter_suffixes!
# or
normalizer.extend(LCSort::AllowLetterSuffixes)
```

Although I'm not sure most users will actually want configuration. It might provide cleaner code either way, even if we don't (initially) provide configuration.  I might benchmark to make sure it doesn't slow things down though, I need performance from this library. 

I definitely also want to handle the "date or other number" that can appear before a cutter, as in `JK1359 46th .M4` or `QA 101 1990 .A101`.  That is standard LC. 

It's unclear how adding those will effect the 'bottomout' option. We need more tests for bottomout, and to think about what we actually want to support. I wonder if `bottomout` actually only needs to be supported for classifications (eg `QA 101.1`) and not for subsequent cutter numbers. I asked Bill Dueber about use cases for bottomout including cutters, but he couldn't remember for sure. If we only support bottomout for class numbers, generated sortkeys can get significantly simpler, we don't need to pad all the cutters. 

I also want to make this thing be able to handle NLM call numbers, which are MOSTLY like LC, but have some different allowable patterns in cutters. I'm still figuring out

**Comment by jrochkind** [comment]
Hey @tampakis, I've got some ideas for some fairly major refactors
- Change the way the normalized strings are constructed a bit, to better accomodate the enhancements we want
- Make the whole thing object-oriented  (`Lcsort.new.normalize(foo)`) to hypothetically allow some easier customization for different local rules. 

Since I have a bunch of stuff I want to work on or experiment with, I've made my own fork and am doing my work there, currently in a branch: https://github.com/jrochkind/lcsort/tree/object_oriented

I'm happy to give you commit rights on my fork if it would make any kind of collaboration easier. Feel free to put a watch on that repo to see my work as it progresses. 

I also plan to share my changes back when I'm doing; I'm not trying to go off with a permanent fork, I just wanted to do a bunch of work to see where it gets me, in a repo I have commit rights to.

**Comment by tampakis** [comment]
Sounds good. I'll watch that repo and see how I can help.

**Comment by jrochkind** [comment]
Hey @tampakis, I've done some MAJOR overhaul of lcsort, over in https://github.com/jrochkind/lcsort/tree/object_oriented

I think it does everything I need now, and has a README. 

Do you want to merge it back in here? Would you consider adding me as a committer here?

It does not handle your lowercase `x` as a cutter prefix to be ignored. I wonder if your org locally is maybe simply using that `x` as an alternative to `.`, and you could pre-process to just turn them into standard `.` by something simple like `gsub(/x([A-Z])/, ".\1"`, or something like that?

**Comment by tampakis** [comment]
@jrochkind this looks awesome! I just give you admin rights on this repository. Submit a PR and I'll merge.

**Comment by jrochkind** [comment]
FYI, our local call number browse is live, eg [here](https://catalyst.library.jhu.edu/shelfbrowse?origin_sort_key=HQ.1587.F4.2004---bib_2444395)

**Comment by jpstroop** [comment]
:+1:
